version: "3"

services:
  facade_service:
    build:
      context: ./facade_service
    ports:
      - "7000:7000"
    depends_on:
      - logging_service
      - messages_service

  logging_service:
    build:
      context: ./logging_service
    ports:
      - "7001:7001"

  messages_service:
    build:
      context: ./messages_service
    ports:
      - "7002:7002"

